"""create gacha tables

Revision ID: 351803a2ed78
Revises: 17859dfb2559
Create Date: 2026-07-15 10:19:00.904569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351803a2ed78'
down_revision: Union[str, Sequence[str], None] = '17859dfb2559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_archetypes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faction', sa.Enum('greek', 'norse', 'egyptian', 'aztec', 'oriental', name='faction'), nullable=False),
    sa.Column('rank', sa.Enum('hero', 'demigod', 'minor_god', 'major_god', name='rank'), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('archetype_id', sa.UUID(), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'rare', 'epic', 'legendary', name='rarity'), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('obtained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['card_archetypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_cards_user_id'), 'player_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_cards_user_id'), table_name='player_cards')
    op.drop_table('player_cards')
    op.drop_table('card_archetypes')
    # ### end Alembic commands ###
    # op.drop_table() no elimina los tipos ENUM de Postgres subyacentes
    # (quedan huérfanos y rompen un upgrade posterior con "type already exists")
    sa.Enum(name='rarity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='rank').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='faction').drop(op.get_bind(), checkfirst=True)
