"""add cards_per_pack to gacha_pack_levels

Revision ID: 6d62457ac750
Revises: de7aafeffe7d
Create Date: 2026-07-15 16:39:34.154375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d62457ac750'
down_revision: Union[str, Sequence[str], None] = 'de7aafeffe7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default agregado a mano (ver docs/architecture.md, "Backend
    # Conventions"): sin esto, ADD COLUMN NOT NULL falla si gacha_pack_levels
    # ya tiene filas -- 5 en cualquier ambiente donde ya corrió el seed.
    op.add_column(
        'gacha_pack_levels',
        sa.Column('cards_per_pack', sa.Integer(), nullable=False, server_default='5'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gacha_pack_levels', 'cards_per_pack')
    # ### end Alembic commands ###
