"""add is_superadmin to users

Revision ID: 8f7dd2b53695
Revises: 351803a2ed78
Create Date: 2026-07-15 11:03:22.109723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7dd2b53695'
down_revision: Union[str, Sequence[str], None] = '351803a2ed78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default agregado a mano: sin esto, ADD COLUMN NOT NULL falla si
    # `users` ya tiene filas (autogenerate no lo detecta).
    op.add_column(
        'users',
        sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
