"""create gacha config tables

Revision ID: de7aafeffe7d
Revises: 8f7dd2b53695
Create Date: 2026-07-15 11:28:59.053053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'de7aafeffe7d'
down_revision: Union[str, Sequence[str], None] = '8f7dd2b53695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Los tipos ENUM "rank" y "rarity" ya existen en Postgres (creados en la
# migración 351803a2ed78 para card_archetypes/player_cards). create_type=False
# evita que op.create_table intente un CREATE TYPE duplicado -> DuplicateObject.
_rank_enum = postgresql.ENUM(
    'hero', 'demigod', 'minor_god', 'major_god', name='rank', create_type=False
)
_rarity_enum = postgresql.ENUM(
    'common', 'rare', 'epic', 'legendary', name='rarity', create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gacha_pack_levels',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('guaranteed_min_rank', _rank_enum, nullable=True),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('gacha_rarity_bonus',
    sa.Column('rarity', _rarity_enum, nullable=False),
    sa.Column('bonus', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('rarity')
    )
    op.create_table('gacha_rank_probabilities',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rank', _rank_enum, nullable=False),
    sa.Column('probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['level'], ['gacha_pack_levels.level'], ),
    sa.PrimaryKeyConstraint('level', 'rank')
    )
    op.create_table('gacha_rarity_probabilities',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rarity', _rarity_enum, nullable=False),
    sa.Column('probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['level'], ['gacha_pack_levels.level'], ),
    sa.PrimaryKeyConstraint('level', 'rarity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gacha_rarity_probabilities')
    op.drop_table('gacha_rank_probabilities')
    op.drop_table('gacha_rarity_bonus')
    op.drop_table('gacha_pack_levels')
    # ### end Alembic commands ###
